### ISSUE TITLE
Comments preceding the TLA+ module break the web explorer

### ISSUE THREAD

**Issue by lemmy** [will62794/tla-web#16]
```tla
a
------------------------------- MODULE Foo -------------------------------
EXTENDS Integers

VARIABLE x

Init ==
	x = 2

Next ==
	x' = 2

=====
```

**Comment by will62794** [comment]
Should be fixed by 38594e4. See [here](https://will62794.github.io/tla-web/?specpath=./specs/with_state_graphs/pre_module_comments.tla#).

And thanks for filing these various issues. At some point I can do a more systematic review of supported/unsupported features and build out the [test suite](https://will62794.github.io/tla-web/test) more thoroughly, but so far I've just been addressing issues as they've appeared in specs I've tried out.
