### ISSUE TITLE
Folds not supported

### ISSUE THREAD

**Issue by oggy-** [will62794/tla-web#35]
I'd like to use folds over sequences, but they don't seem to be supported. See an example below. I assume that recursive definitions are tricky to add? Could you suggest a workaround? This is at the moment a bit of a blocker for me - I'd like to use tla-web as "interactive docs" for some of the subsystems I've modeled in TLA, but the models do rely on folds.

```
---- MODULE Web ----

\* The following two definitions are copied verbatim from the community modules
MapThenFoldSet(op(_,_), base, f(_), choose(_), S) ==
  LET iter[s \in SUBSET S] ==
        IF s = {} THEN base
        ELSE LET x == choose(s)
             IN  op(f(x), iter[s \ {x}])
  IN  iter[S]

FoldLeft(op(_, _), base, seq) == 
  MapThenFoldSet(LAMBDA x,y : op(y,x), base,
                 LAMBDA i : seq[i],
                 LAMBDA S : Max(S),
                 DOMAIN seq)


VARIABLE
    seq,
    val

Init ==
    /\ seq = << 1, 2, 3 >>
    /\ val = FoldLeft(LAMBDA x, y: x + y, 0, seq)

Next == UNCHANGED << seq, val >>
   
====
```

**Comment by will62794** [comment]
@oggy- Sorry for the delay, but I think this issue is at least partially addressed now. See a (slightly modified) working example [here](https://will62794.github.io/tla-web/#!/home?specpath=./specs/with_state_graphs/simple_folds.tla). 

I added initial support for recursive function definitions (be2f721), so that should no longer be a blocker here. Note that I modified the operator definitions slightly to make argument names unique. In the example you gave, it seems there may be a few subtle issues around how the interpreter handles LAMBDA expressions in nested operator calls like this. These issues may need to be ironed out fully in the future. For now, though, a reasonable workaround seems to be manually enforcing uniqueness of operator argument names where necessary. You can see if this gets you unblocked for now.
